/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseRelayRecipient } from "./BaseRelayRecipient";
export type { IRelayRecipient } from "./IRelayRecipient";
export type { Ownable } from "./Ownable";
export type { ERC1155 } from "./ERC1155";
export type { IERC1155MetadataURI } from "./IERC1155MetadataURI";
export type { IERC1155 } from "./IERC1155";
export type { IERC1155Receiver } from "./IERC1155Receiver";
export type { ERC1155Holder } from "./ERC1155Holder";
export type { ERC1155Receiver } from "./ERC1155Receiver";
export type { ERC165 } from "./ERC165";
export type { IERC165 } from "./IERC165";
export type { Base } from "./Base";
export type { Configuration } from "./Configuration";
export type { Monetizable } from "./Monetizable";
export type { DesperadosTokens } from "./DesperadosTokens";
export type { DesperadosCore } from "./DesperadosCore";
export type { DesperadosWorld } from "./DesperadosWorld";
export type { WorldActionMining } from "./WorldActionMining";
export type { WorldBase } from "./WorldBase";

export { BaseRelayRecipient__factory } from "./factories/BaseRelayRecipient__factory";
export { IRelayRecipient__factory } from "./factories/IRelayRecipient__factory";
export { Ownable__factory } from "./factories/Ownable__factory";
export { ERC1155__factory } from "./factories/ERC1155__factory";
export { IERC1155MetadataURI__factory } from "./factories/IERC1155MetadataURI__factory";
export { IERC1155__factory } from "./factories/IERC1155__factory";
export { IERC1155Receiver__factory } from "./factories/IERC1155Receiver__factory";
export { ERC1155Holder__factory } from "./factories/ERC1155Holder__factory";
export { ERC1155Receiver__factory } from "./factories/ERC1155Receiver__factory";
export { ERC165__factory } from "./factories/ERC165__factory";
export { IERC165__factory } from "./factories/IERC165__factory";
export { Base__factory } from "./factories/Base__factory";
export { Configuration__factory } from "./factories/Configuration__factory";
export { Monetizable__factory } from "./factories/Monetizable__factory";
export { DesperadosTokens__factory } from "./factories/DesperadosTokens__factory";
export { DesperadosCore__factory } from "./factories/DesperadosCore__factory";
export { DesperadosWorld__factory } from "./factories/DesperadosWorld__factory";
export { WorldActionMining__factory } from "./factories/WorldActionMining__factory";
export { WorldBase__factory } from "./factories/WorldBase__factory";
