/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface WorldBaseInterface extends ethers.utils.Interface {
  functions: {
    "completeWorldActionCooldown(address)": FunctionFragment;
    "getCompleteWorldActionCooldownEstimatedFee(address)": FunctionFragment;
    "getCurrentWorldActionCooldownFor(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setBaseFee(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdraw()": FunctionFragment;
    "worldActionASuccessProbabilities(uint256)": FunctionFragment;
    "worldActionCooldowns(uint256)": FunctionFragment;
    "worldActionCooldownsSeconds(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "completeWorldActionCooldown",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCompleteWorldActionCooldownEstimatedFee",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentWorldActionCooldownFor",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "worldActionASuccessProbabilities",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "worldActionCooldowns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "worldActionCooldownsSeconds",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "completeWorldActionCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCompleteWorldActionCooldownEstimatedFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentWorldActionCooldownFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBaseFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "worldActionASuccessProbabilities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "worldActionCooldowns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "worldActionCooldownsSeconds",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class WorldBase extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: WorldBaseInterface;

  functions: {
    completeWorldActionCooldown(
      _caller: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCompleteWorldActionCooldownEstimatedFee(
      _caller: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { estimatedFeeToPay: BigNumber }>;

    getCurrentWorldActionCooldownFor(
      _caller: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [number, BigNumber] & {
          actionType: number;
          cooldownTimestamp: BigNumber;
        }
      ]
    >;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBaseFee(
      baseFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    worldActionASuccessProbabilities(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    worldActionCooldowns(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    worldActionCooldownsSeconds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;
  };

  completeWorldActionCooldown(
    _caller: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCompleteWorldActionCooldownEstimatedFee(
    _caller: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCurrentWorldActionCooldownFor(
    _caller: string,
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber] & { actionType: number; cooldownTimestamp: BigNumber }
  >;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBaseFee(
    baseFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  worldActionASuccessProbabilities(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  worldActionCooldowns(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  worldActionCooldownsSeconds(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  callStatic: {
    completeWorldActionCooldown(
      _caller: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getCompleteWorldActionCooldownEstimatedFee(
      _caller: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentWorldActionCooldownFor(
      _caller: string,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber] & { actionType: number; cooldownTimestamp: BigNumber }
    >;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setBaseFee(baseFee: BigNumberish, overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(overrides?: CallOverrides): Promise<void>;

    worldActionASuccessProbabilities(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    worldActionCooldowns(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    worldActionCooldownsSeconds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    completeWorldActionCooldown(
      _caller: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCompleteWorldActionCooldownEstimatedFee(
      _caller: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCurrentWorldActionCooldownFor(
      _caller: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBaseFee(
      baseFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    worldActionASuccessProbabilities(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    worldActionCooldowns(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    worldActionCooldownsSeconds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    completeWorldActionCooldown(
      _caller: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCompleteWorldActionCooldownEstimatedFee(
      _caller: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentWorldActionCooldownFor(
      _caller: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBaseFee(
      baseFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    worldActionASuccessProbabilities(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    worldActionCooldowns(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    worldActionCooldownsSeconds(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
